### ISSUE TITLE
Web 版在 Android 下很难复制生成的密码

### ISSUE THREAD

**Issue by glacjay** [cyfdecyf/mypass#2]
因为密码生成框是禁止编辑的，虽然点击之后就自动全选了整个密码，但并不会出现上面的复制、剪切等的工具栏，每次都是碰运气试好长时间不知道怎么胡乱操作一下才能出现。不知道能不能增加一个「复制」按钮，能把密码复制到剪贴板。不行的话也可以去掉禁止编辑的属性。

**Comment by cyfdecyf** [comment]
我不确定 Android 的浏览器是否提供了拷贝到剪贴板的 API，像在 Chrome/Safari 上是没有这样的 API 的，之前查过这个功能必须通过 flash 才能实现。

MyPass 的 iOS 版本是把密码放在一个 label 中，在手机上更容易选中。你可以考虑帮忙做个 Android 优化的版本，比如支持放到主屏幕直接打开 MyPass 的页面。

**Comment by glacjay** [comment]
Chrome 已经支持直接将某个网址添加到主屏上了，打开之后连地址栏都访问不了，搞得就像一个真正的应用似的。

**Comment by cyfdecyf** [comment]
iOS Safari 也支持这个功能，iOS 的网页版是针对 web app 做了优化，主要是设置了高清图标，可以离线使用。

Android 估计也有这样的支持，不过网页应该也要做点修改吧。

**Comment by glacjay** [comment]
Android 上不需要做修改，直接就能用了。

**Comment by cyfdecyf** [comment]
既然 Android 兼容的话那手机上直接用 iOS 版的页面吧。
