### ISSUE TITLE
[REJECTED] Improving Mypass

### ISSUE THREAD

**Issue by sergeevabc** [cyfdecyf/mypass#3]
Dear Chen,
could you be so kind and improve MyPass in some ways? 
- declutter popup by collapsing section with symbols/length/etc ([like here](https://chrome.google.com/webstore/detail/bpasswd/dfehiejdcgoiofnfkdippnfadgdpnmlh/))
- show popup immediately after click (current delay is about 1 second, compare with [PasswordGen](https://github.com/eterevsky/passwordgen))
- option _not_ to save per-site preferences at all (hence nothing to sync with Google as well)
- option to auto-insert subdomain+domain (e.g. diary.livejournal.com, workblog.livejournal.com)
- option to store masterkey in memory until the browser is closed ([like here](https://github.com/eterevsky/passwordgen/blob/gh-pages/images/screenshot2.png))
- replace bluish messages like “Generate your password” with buttons [Insert], [Copy], [Options]
- rename “Passphrase” into “Masterkey” so not to be confused with “Password” field

**Comment by cyfdecyf** [comment]
Thanks for your valuable suggestions.

I've considered features like insert and copy password. Insert would be easy to implement but copy requires flash. The main problem is that I'm not familiar with Javascript and HTML, implementing these features and improving the UI would take me quite some time.

I do not feel safe to store the master key in memory. As I mainly use OS X, I've considered using Keychain to store master key and only grant access only to MyPass app/extension. But I'm not familiar with OS X development and this would require maintaining another version of MyPass.

For now, MyPass is mainly used by myself and a few of my friends, and it works well for us. So I don't have a strong motivation to improve it, especially considering the amount of time needed.
